services:
  - type: web
    name: eira-maison
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MONGO_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: VITE_API_BASE_URL
        value: https://eira-n6zn.onrender.com/api
      - key: VITE_ENV
        value: production
